### ISSUE TITLE
subLang doesn't get the proper subtitles for a few series

### ISSUE THREAD

**Issue by Oujiii** [izu-co/funimation-downloader-nx#1]
Ok, so following your latest advice I was able to define `subLang` on `cli-defaults.yml` and then I tested on an episode that I know has the pt (Portuguese) language. I will past a part of the output only to avoid unnecessary text. This also happens if I pass the value as an argument. I had already noticed this behaviour yesterday on a few series which the error message would be similar, like this: 
`[WARN] Unable to find subtitle language 'en'. Defaulting to English.`

But this was before I realize I could download something else other than English subs. I noticed that if I comment out the `subLang`, it will download in English, but not throw the error. That is kinda weird for me, not gonna lie.

```
[INFO] Kaguya-sama: Love is War - S2E01 - Ai Hayasaka Wants to Stave Them Off / The Student Council Has Not Achieved Nirvana / Kaguya Wants to Get Married / Kaguya Wants to Celebrate
[INFO] Available streams (Non-Encrypted):
[WARN] Unable to find subtitle language 'pt'. Defaulting to English.
[#1079007] Japanese [Simulcast] (selected)
[#1136851] English [Simulcast] 
```

Forgot to mention that I downloaded only the subs for Shadows House and it worked. Just tried the whole episode and it also selects the right subtitle.

**Comment by STRATOS99K** [comment]
This might be because funimation used to store the subs without a language identifier like english_full.vtt, spanishlatinamerica_full.vtt, but like this 669c5c23-5a75-445d-affd-787061998b09.vtt instead so these shows will have 3 subs, you can get them with netmon, they should be in this order
Portuguese
Spanish
English
But like I said there's no clear identifier for me

**Comment by Oujiii** [comment]
Netmon? What is this? 
Right now I also can't pass these names as variables, if they have both subs with tagged as en, es and pt and Portuguese, Spanish, English, this might be hard. The good thing about the tool is that I can automate several downloads, the bad thing is that I can't be sure I will get the subs I want, only when I actually watch it. Funimation likes to complicate stuff.

**Comment by STRATOS99K** [comment]
> Netmon? What is this?
> Right now I also can't pass these names as variables, if they have both subs with tagged as en, es and pt and Portuguese, Spanish, English, this might be hard. The good thing about the tool is that I can automate several downloads, the bad thing is that I can't be sure I will get the subs I want, only when I actually watch it. Funimation likes to complicate stuff.

Netmon, network monitor addon, there are others that can get you the m3u8 and vtt links from funimation if you open a video

**Comment by izu-co** [comment]
Alrighty so as it turns out I forgot to watch my own repo and therefore didn't receive an email.

Anyway I will look into it, and sorry for the delay!

**Comment by Oujiii** [comment]
No worries, thank you for looking into it and let me know if you need anything from my end!

**Comment by izu-co** [comment]
@Oujiii If you would be so kind and test the changes I made?

You can now see which streams don't have the sub language you requested. 
```
[INFO] Available streams (Non-Encrypted):
[#1078991] Japanese [Simulcast] (selected)
[#1273566] English [Simulcast]  (defaulted to Englisch subtitles)
```

So in this case you can download the Japanese video with esLA subtitles but not the English one (for whatever reason the English version only has English subtitle).

**Comment by Oujiii** [comment]
Hmmm, you commited a new PR and I forgot to update. My bad. Let me do it again.

**Comment by izu-co** [comment]
I think it's because ```--subLang pt``` isn't possible any more.

I changed it so ```--dub``` and ```--subLang``` are the same. Try ```prBR```.

**Comment by Oujiii** [comment]
This has been solved now. I just pushed a PR to fix a typo, but other than that everything worked. If the subs are available, they will be download, if they are not available, it will default to English, as it should be.

**Comment by izu-co** [comment]
Nice to hear and glad that I could help.
