### ISSUE TITLE
[BUG] Wrong Audio Flag

### ISSUE THREAD

**Issue by Astyre** [izu-co/funimation-downloader-nx#13]
** Main info: **

Script version: 4.9.0
Show ID: 1315001
Episode ID: 0007

** Additional Info: **
When I try to download the most recent version of the show listed above using the following command "node funi -s 1315001 -q 0 --mks --dub enUS --dub jpJP --fileName "${showTitle} - S${season}E${episode} - ${title}" -e 7" it will download the english audio as a separate .ts file, it then downloads the Japanese audio and video as one file. When it goes to mux it all together it flags both tracks as eng when the first track in the file should be labeled as jap.

Below is the mkvmerge command that it uses where you can see it assigns the Japanese track the English flag.

"mkvmerge" -o "G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --video-tracks 0 --audio-tracks 1 --track-name 0:[Funimation] --language 1:eng "G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.video.jp.ts" --language 0:eng --no-video --audio-tracks 0 "G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.audio.en.ts" --language 0:eng "G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.subtitle.enUS.ass"
mkvmerge v48.0.0 ('Fortress Around Your Heart') 64-bit
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.video.jp.ts': Using the demultiplexer for the format 'MPEG transport stream'.
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.audio.en.ts': Using the demultiplexer for the format 'AAC'.
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.subtitle.enUS.ass': Using the demultiplexer for the format 'SSA/ASS subtitles'.
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.video.jp.ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.video.jp.ts' track 1: Using the output module for the format 'AAC'.
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.audio.en.ts' track 0: Using the output module for the format 'AAC'.
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.subtitle.enUS.ass' track 0: Using the output module for the format 'text subtitles'.
The file 'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.mkv' has been opened for writing.
'G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.video.jp.ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 8 seconds.

Below is the mediainfo from the resulting file showing both tracks flagged as english.

General
Unique ID                                : 0 (0x0)
Complete name                            : G:\funimation-downloader-nx-master\videos\Bottom-Tier Character Tomozaki - S01E07 - When a mentor character becomes a boss, they'll push you to the edge.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.04 GiB
Duration                                 : 23 min 47 s
Overall bit rate                         : 6 272 kb/s
Writing application                      : no_variable_data
Writing library                          : no_variable_data

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 23 min 47 s
Nominal bit rate                         : 6 500 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.131
Title                                    : [Funimation]
Writing library                          : x264 core 157 r2948 dada181
Encoding settings                        : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=2 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=48 / keyint_min=4 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=cbr / mbtree=1 / bitrate=6500 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=6500 / vbv_bufsize=19500 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No
Duration_Source                          : General_Duration

Audio #1
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 23 min 47 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -43 ms
Language                                 : English
Default                                  : Yes
Forced                                   : No
Duration_Source                          : General_Duration

Audio #2
ID                                       : 3
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 23 min 47 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -43 ms
Language                                 : English
Default                                  : No
Forced                                   : No
Duration_Source                          : General_Duration

Text
ID                                       : 4
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Language                                 : English
Default                                  : Yes
Forced                                   : No

On episodes where both the English and Japanese audio are downloaded separately from the video it flags them both appropriately.

**Comment by izu-co** [comment]
Looking into it

**Comment by izu-co** [comment]
Please see [this update](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.9.1).

**Comment by Astyre** [comment]
Works perfectly, downloaded the same episode and it flagged each track appropriately.

Thank you for looking into it.
