### ISSUE TITLE
a thank you and a request

### ISSUE THREAD

**Issue by OryWareKyrie** [izu-co/funimation-downloader-nx#15]
first i want to thank dev for the tool. the [anidl](https://github.com/anidl/funimation-downloader-nx) tool is full of bugs and the project is not very active. secondly, i want you to take a look at this bug of the [CR tool](https://github.com/anidl/crunchyroll-downloader-nx/issues/39), made by anidl. if you can of course. by any chance do you have any means of contact? preferably telegram or discord. I have some ideas for the tool I would like to talk to you about. unfortunately I'm not knowledgeable about programming and I'm sorry I can't help.

Edit: Telegam: @OryWareKyrie Discord: 𝓞𝓻𝔂𝓦𝓪𝓻𝓮 𝓚𝔂𝓻𝓲𝓮#4772

**Comment by izu-co** [comment]
I only maintain this tool because some friends want me to.

I unfortunately don’t have the to maintain all tools by anidl. So I won’t make any changes to the crunchyroll downloader.

**Comment by OryWareKyrie** [comment]
> I only maintain this tool because some friends want me to.
> 
> I unfortunately don’t have the to maintain all tools by anidl. So I won’t make any changes to the crunchyroll downloader.

OK! thank you very much anyway. :smile:

**Comment by izu-co** [comment]
By the way, if you think your proposals may be of use to this downloader, just tell them to me in another comment. 
I'm always open for feedback!

**Comment by OryWareKyrie** [comment]
> By the way, if you think your proposals may be of use to this downloader, just tell them to me in another comment.
> I'm always open for feedback!

would love to give my opinion and ideas. but around here on github it's not very "fluid". I'm still testing it on my friend's PC, windows 10 x64, in the united states, via anydesk. for now I came across an error while downloading. out of nowhere it stops downloading. it has already happened 3 times. just to let you know that I can't speak English and I'm using google translator, in case the translation is wrong.
