### ISSUE TITLE
[BUG] Not selecting Sub only shows

### ISSUE THREAD

**Issue by cimmy01** [izu-co/funimation-downloader-nx#16]
When trying to download a sub only show I will not select the track for the Japanese version. 

Script version: 4.9.1
Show ID: 1643752
Episode ID: 1

C:\Users\cimmy\Desktop\funimation-downloader-nx-4.9.1-win64>funi -s 1643752 -q 0 --sublang enUS -e 1

=== Funimation Downloader NX 4.9.1 ===

[#1643752] Kageki Shojo!! (2021)
[0001] Kageki Shojo!! - #01 Episode 1 Title (00:24:09) [SD540, Japanese] (selected)

[INFO] Selected Episodes: 0001

[INFO] Kageki Shojo!! - S1E1 - Episode 1 Title
[INFO] Available streams (Non-Encrypted):
[#1650655] Japanese [Simulcast]
[ERROR] Track not selected

**Comment by OryWareKyrie** [comment]
friend is not a bug. you just didn't set the flags. try this **```funi -s 1643752 -q 0 --sublang enUS -e 1 --noaudio --dub jaJP --novids --simul```** :smile:

**Comment by izu-co** [comment]
Jup it is indeed not a bug. If you want subs only just add —novids and —noaudio

**Comment by cimmy01** [comment]
its not even downloading the show not just he subs

**Comment by izu-co** [comment]
You have to use —dub jaJP (please see the help if this is correct, since I am currently unsure).

with the new update the Tool is downloading subtitles corresponding to there dub.
so select Japanese dub to get the subtiles associated with it (like e.g. English)

**Comment by cimmy01** [comment]
looks like it is
