### ISSUE TITLE
problem with downloading only subtitles.[BUG] 

### ISSUE THREAD

**Issue by levaculik2** [izu-co/funimation-downloader-nx#19]
** Main info: **

Script version: 4.9.1 / 4.9.2
Show ID: 1326227
Episode ID: All Episodes

** Additional Info: **

=== Funimation Downloader NX 4.9.2 ===

./funi -s 1326227 --all -q 10 --dub jaJP --subLang "enUS" "esLA" "ptBR" --noaudio --novids

[INFO] Saint Seiya: The Lost Canvas - S1E1 - Promise
[INFO] Available streams (Non-Encrypted):
[#1326492] Japanese [Uncut] (selected) (using 'English', 'Spanish (Latin Am)', 'Portuguese (Brazil)' for subtitles)

whenever I download only the subtitles instead of the tool get all subtitles it is getting only the first subtitle for all episodes.

Am I doing it wrong???
![episodio01](https://user-images.githubusercontent.com/57818248/125968870-c99ad7f8-1a75-4312-8939-16334ed18548.png)
![episodio02](https://user-images.githubusercontent.com/57818248/125968875-3b996c3f-ebe2-4a1e-aa01-3c8f8a603ed3.png)

**Comment by izu-co** [comment]
Yes you are. Either use —allsubs (see help for casing) or chain them by doing —suglang enUs —sublang esLa

**Comment by levaculik2** [comment]
hello did what you said using --allsubs and --subLang ''ptBR" --subLang "enUS" --subLang "esLA" until it worked it actually pull all the subtitles, but the problem is not pulling the subtitles correct.this coming only the subtitles of the first episode for all other episodes.same as I posted in the images .both episodes are with the same subtitles.

**Comment by izu-co** [comment]
Can you give me the complete console output along with an image of the output folder?

**Comment by DragonVsKira** [comment]
i try both of then he/she is right 
im going to say this is the code
funi -s 1326227 --all -q 10 --dub jaJP --allsubs --noaudio --novids
funi -s 1326227 --all -q 10 --dub jaJP --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids

<img width="1706" alt="Screenshot 2021-07-17 052101" src="https://user-images.githubusercontent.com/35433196/126036729-bf748ace-1219-48e4-bfd6-9d4216eb5c18.png">

**Comment by levaculik2** [comment]
I tested it the same way that DragonVsKira did.and the same example that I put in the images happened.that's not what happens only in this anime, it happened in all the animes I downloaded.

**Comment by DragonVsKira** [comment]
it a bug with the "--all" because this work just find
```
funi -s 1326227 -e "1" -q 10 --dub jaJP --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids
funi -s 1326227 -e "2" -q 10  --dub jaJP --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids
```
<img width="1706" alt="Screenshot 2021-07-17 054929" src="https://user-images.githubusercontent.com/35433196/126037648-35531797-55c0-406e-87cb-ad0ac90e2ee4.png">

is did not work either 
funi -s 1326227 -e 1-26 -q 10 --dub jaJP --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids

<img width="1703" alt="Screenshot 2021-07-17 060230" src="https://user-images.githubusercontent.com/35433196/126037797-839f40e1-669d-43ad-b842-9daeddb832ad.png">

i try on Dragon Ball but it the same did not work 
funi -s 27295 -e 1-26 -q 10  --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids

is work again 
funi -s 27295 -e 1 -q 10  --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids
funi -s 27295 -e 2 -q 10  --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids

so now i now it buggy out when it selected multiple ep at start or something like that 
i hope this helps at all

**Comment by levaculik2** [comment]
this bug is happening when you try to download all episodes. if you do one at a time it doesn't happen. to get around this i'm making a batch file. with a command for each episode.

**Comment by DragonVsKira** [comment]
> this bug is happening when you try to download all episodes. if you do one at a time it doesn't happen. to get around this i'm making a batch file. with a command for each episode.

that what i said lol 
i use a batch file to do my testing lol
but your is easier to read lol

**Comment by izu-co** [comment]
So to sum it up this issue only happens if you download mutliple episodes at onec

**Comment by DragonVsKira** [comment]
yes

**Comment by DragonVsKira** [comment]
any update for this just asking that all

**Comment by izu-co** [comment]
I actually just entered my holidays so you can expect an update within the next few days

**Comment by izu-co** [comment]
@DragonVsKira @levaculik2 Please see https://github.com/izu-co/funimation-downloader-nx/commit/56d836c4ee94e0aa046a2cba93223970f282b72f. It should have fixed the issue.
You can get the new release fom [here](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.9.4)

**Comment by levaculik2** [comment]
izu-co looks like it's still having a problem, I just tested this version that you have available and it continues to damage the same error with the subtitles. As you can see in the example, the same subtitle is still coming.
![errolegenda](https://user-images.githubusercontent.com/57818248/126876327-d202a697-f7ed-42c6-ae6d-0e8272eb5e61.png)

**Comment by izu-co** [comment]
You are using the newest version, are you?
Can you give me your exact command?

**Comment by levaculik2** [comment]
This I'm using this new version that you make available. Release 4.9.4.
as I said I used this command

funi -s 1400603 -e 0001-0002 -q 10 --dub jaJP --allSubs --skipmux

**Comment by izu-co** [comment]
I will test it later

**Comment by DragonVsKira** [comment]
work fine for me with the new update 
<img width="1880" alt="Screenshot 2021-07-24 151417" src="https://user-images.githubusercontent.com/35433196/126882419-4719c92a-7c3d-4d0a-b2c5-d1ca418311d8.png">
<img width="1880" alt="Screenshot 2021-07-24 151847" src="https://user-images.githubusercontent.com/35433196/126882420-70ea920f-17e7-4e44-a6ca-6a468386c2f1.png">

thanks you thanks you

**Comment by DragonVsKira** [comment]
i try
funi -s 1400603 --all -q 10 --dub jaJP --allSubs --skipmux
funi -s 1400603 -e 0001-0002 -q 10 --dub jaJP --allSubs --skipmux
funi -s 27295 -e 1-26 -q 10  --subLang "ptBR" --subLang "enUS" --subLang "esLA" --noaudio --novids
all seem to work now

**Comment by izu-co** [comment]
@DragonVsKira No prob
@levaculik2 On that note can you redownload the Update?

**Comment by DragonVsKira** [comment]
@izu-co im glad to help you out with testing lol

**Comment by izu-co** [comment]
@DragonVsKira You mean testing new updates? If so I am sure to ping you

**Comment by DragonVsKira** [comment]
yes

**Comment by izu-co** [comment]
@DragonVsKira Just for me as reference, where are you from?

**Comment by DragonVsKira** [comment]
CA and you

**Comment by izu-co** [comment]
Germany.

Anyway, we shouldn't continue this conversation here. You can replay to me in #25.

As far as this issue goes, please try to redownload the newest version. If you've done that, and it still doesn't work, feel free to reopen this issue.
