### ISSUE TITLE
Can i get Support for Funimation-nx

### ISSUE THREAD

**Issue by DragonVsKira** [izu-co/funimation-downloader-nx#20]
if it possible to add the audio language to this --fileName it will help out when u use  --all because it download everything or maybe add a --allDub,allJap something like that 
if it possible if not i just have to check what episode dub stop at lol like One Piece i use  --all it and im like im behind lol i play some's ep it was only sub then i was ok time to ask you if u can add is if not it ok

then i seen u add it --dub,--allDubs,--allSubs

**can i get a Examples how to use them --dub,--allDubs,--allSubs**
i try 

`funi.exe -s 20224 --allDubs --fileName "${showTitle} - S${season}E${episode} - ${title} - [${height}p] [FuniDub][DVK]"`
but i get this  
**[INFO] Episodes not selected!**

all the information i can get was this 
--dub               Download non-Japanese Dub (English Dub mode by default)[array] [choices: "enUS", "esLA", "ptBR", "zhMN", "jaJP"] [default: "enUS"]

--allSubs           If set to true, all available subs will get downloaded   
--allDubs           If set to true, all available dubs will get downloaded

did --sub get remove because it not working no more

ps Thanks you 4 all your hard work

**Comment by izu-co** [comment]
If you do allsubs you still have to choose the episodes with —all oder -e

**Comment by izu-co** [comment]
And yes --sub has been removed

**Comment by DragonVsKira** [comment]
**is it possible to add the Dubs language to --fileName**? just asking if it to much work all good 
just glad u r sharing this with people 

does allsubs download subtitles or Japanese Dub? i thank me and alot of eng dub people get lose because we just call Japanese Dub = sub lol

if i thank im right it go like this
--allSubs download all language subtitles that available 
--allDubs  all available language 

**if i knows anything about JavaScript i would help u out**
