### ISSUE TITLE
Unable to specify `videoLayer: 0` for "-q 0"

### ISSUE THREAD

**Issue by toukoaozaki** [izu-co/funimation-downloader-nx#21]
Current evaluation logic is unable to handle

`videoLayer: 0`

since `cfg.videoLayer || 7` will evaluate to 7, instead of 0.

**Comment by DragonVsKira** [comment]
im i little lost what r u trying to do can i get more information please

**Comment by toukoaozaki** [comment]
IIUC `config/cli-defaults.yml` contains default arguments for files. This is loaded via `modules/module.app-args.js`.

The desired behavior is to be able to set the default quality (`cfg.videoLayer`, set by `-q` flag) to 0, aka "max". The only way to express this is to modify `config/cli-defaults.yml` to have a line that says `videoLayer: 0`.

Since the code setting the default uses `||`, a value of 0 will be superseded with the default `7`, which is not desired when an explicit value of 0 is specified. Instead, the code should explicitly check for an unset value (undefined?) instead of relying on logical OR operator.

**Comment by DragonVsKira** [comment]
i thanks maybe -q 0 go remove or something  but 10 = aka "max" i tested 10 and that work or u can wait for izu-co to help you out sorry that i was no help :(

**Comment by izu-co** [comment]
Yes indeed the behaviour is wrong and still from anidl.

I am currently not home so I will hit you up with a fix once I am.

**Comment by izu-co** [comment]
Please see [this release](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.9.3) for the updated version.
