### ISSUE TITLE
Answering audio rewrite prompt 'N' results in mux failure

### ISSUE THREAD

**Issue by toukoaozaki** [izu-co/funimation-downloader-nx#22]
** Main info: **

Script version: 4.9.2
Show ID: 847520
Episode ID: M001

** Additional Info: **

```
[INFO] Finished /mnt/c/Users/<>/funimation-downloader-nx2/videos/[Funimation] Demon Slayer_ Kimetsu no Yaiba - Movie1 [1080p].video.ts
[Q] File «/mnt/c/Users/<>/funimation-downloader-nx2/videos/[Funimation] Demon Slayer_ Kimetsu no Yaiba - Movie1 [1080p].audio.ja.ts» already exists! Rewrite? (y/N): n

[INFO] Unable to locate a video AND audio file
```

**Comment by DragonVsKira** [comment]
what happened if u say yes r remove all Demon Slayer_ Kimetsu no Yaiba - Movie1 file and try again 
can i get the cmd commands your using ill try it on my end maybe i can help you

**Comment by toukoaozaki** [comment]
Saying "y" to download again generally works. I've observed this across multiple instances of retries needed from partial failures and generally the issues observed are due to transient download errors.

I've manually muxed the audio and video using `mkvmerge` so I don't have any remaining issues myself, but the bug still remains in the script.

Based on my read, the issue seems to be the fact that `downloadFile` treats "N" the same way as it deals with failure by returning false.

```
        let rwts = await shlp.question(`[Q] File «${filename + '.ts'}» already exists! Rewrite? (y/N)`);
        rwts = rwts || 'N';
        if (!['Y', 'y'].includes(rwts[0])) {
            return false;
        }
        fs.unlinkSync(filename + '.ts');
```
IMHO returning `true` to simply treat the existing file as "good" would be a better solution, considering partial download success/failure seems to happen semi-regularly. Otherwise, perfectly fine partial downloads need to be thrown away and repeated in order to complete the process.

While there is a bit of risk of bad existing file being used in the muxing process, this would only happen when the user has already placed a file with the same name, which should be a rare occurrence.

**Comment by DragonVsKira** [comment]
im dl all One Piece right  now with  0 problem
u can wait for izu-co to help you out sorry that i was no help :(
that y i ask  4 your cmd commands your using
im using 
`funi.exe -s 124389 -e 1  --fileName "${showTitle} - S${season}E${episode} - ${title} - [${height}p] [FuniDub]`
gave or take

**Comment by izu-co** [comment]
The problem is that the tool does not know if the file provided is the correct one. 

I may add a c or continue option for using the video

**Comment by izu-co** [comment]
Please see [this release](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.9.3) for the updated version.
