### ISSUE TITLE
403 Forbidden for one single episode, please help

### ISSUE THREAD

**Issue by Flippette** [izu-co/funimation-downloader-nx#24]
** Main info: **
I tried downloading season 2 of kaguya-sama, but for some reason only episode 10 doesn't work. Everything else does.
Script version: 4.9.3
Show ID: 800793
Episode ID: 22

** Additional Info: **
Command used: ```node funi -s 800793 -e 22 -q 0 --sub enUS --dub jaJP```
Logfile with ```--debug```: [debug.txt](https://github.com/izu-co/funimation-downloader-nx/files/6872354/debug.txt)

**Comment by izu-co** [comment]
I am unable to replicate your issue.
I would recommend reauthentication or switching VPN Servers (if a VPN was used).

**Comment by DragonVsKira** [comment]
[INFO] Selected Episodes: 0007

[INFO] My Hero Academia - S1E7 - Deku vs. Kacchan
[INFO] Available streams (Non-Encrypted):
[#136901] English [Simulcast]
[#132828] Japanese [Simulcast]
[#293900] English [Uncut] (selected) (using 'English' for subtitles)
[#787536] Japanese [Uncut]
[#1619138] Spanish (Latin Am) [Uncut]
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (531KiB/s)
         2: 480x270 (775KiB/s)
         3: 640x360 (1001KiB/s)
         4: 640x360 (1704KiB/s)
         5: 960x540 (2393KiB/s)
         6: 1280x720 (3008KiB/s)
         7: 1280x720 (4341KiB/s)
         8: 1440x810 (6201KiB/s) work 

does not 
```
9: 1920x1080 (7973KiB/s)
10: 1920x1080 (9442KiB/s)
```
[INFO] Selected layer: 10 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/1605014/English/1605014_English_7491086_ee8068b5-32ee-e611-80c5-0017a4776c06_Layer10.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8xNjA1MDE0L0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyODA2MTY5NX19fV19&Signature=bT8Lh9EaTzu3DAO1XRO32l9wj69eNdja3ttg4uU3TxiutcpiP6fYM5hTdea0U0bpZBQ3flp2M7LKRjfiMZiHvpZMIkhmp5CEcATyNM46vd2UA~DOW46~8JffX5TePWcFPZl3T5Oo76H2UzLHjykHgNegMPEX7s6s8kI08nqJrejQU0io~y6iKbY7mv9gFUxZH63Tmy5pgkY-NsPM3R1aKBOEmMTsYvNrL~RcgY02oiGc9ijqR6-o49qKEw~IIwpW6F6PPXEcr6v6Fem~xaEnU7JQWtr7pcfdLtEchAxN~mrggm2cwWYKtDfmmzyYk1FKrXA~Yz7dFOX-qGdP~lUoqQ__&rt=1463498
[INFO] Output filename: My Hero Academia - S01E07 - Deku vs. Kacchan - [1080p] [FuniDub][DVK].ts
[INFO] Started X:\videos\My-Hero-Academia\My Hero Academia - S01E07 - Deku vs. Kacchan - [1080p] [FuniDub][DVK].video.en.ts
[INFO] 10 of 183 parts downloaded [5%] (1m27s)
[INFO] 20 of 183 parts downloaded [11%] (1m16s)
[INFO] 30 of 183 parts downloaded [16%] (1m08s)
[INFO] 40 of 183 parts downloaded [22%] (1m05s)
[INFO] 50 of 183 parts downloaded [27%] (1m00s)
[INFO] 60 of 183 parts downloaded [33%] (54s)
[INFO] 70 of 183 parts downloaded [38%] (50s)
[INFO] 80 of 183 parts downloaded [44%] (46s)
[INFO] 90 of 183 parts downloaded [49%] (41s)
[INFO] 100 of 183 parts downloaded [55%] (37s)
[INFO] 110 of 183 parts downloaded [60%] (33s)
[INFO] 120 of 183 parts downloaded [66%] (29s)
[INFO] 130 of 183 parts downloaded [71%] (24s)
[INFO] 140 of 183 parts downloaded [77%] (20s)
[INFO] 150 of 183 parts downloaded [82%] (15s)
[INFO] 160 of 183 parts downloaded [87%] (10s)
[INFO] 170 of 183 parts downloaded [93%] (6s)
**[ERROR] HTTPError: Response code 403 (Forbidden)**
[ERROR] An error occured while downloading X:\videos\My-Hero-Academia\My Hero Academia - S01E07 - Deku vs. Kacchan - [1080p] [FuniDub][DVK].video.en.ts
[INFO] Downloading subtitles...
[INFO] Subtitles downloaded!

[INFO] Unable to locate a video AND audio file

**Comment by izu-co** [comment]
Sounds strange

**Comment by izu-co** [comment]
I myself have this episode in quality 10 but I will test it later

**Comment by izu-co** [comment]
Was able to reproduce it, but further testing is needed (since I have no clue why it fails).

**Comment by DragonVsKira** [comment]
ok

**Comment by Jaynator495** [comment]
I have this same problem with this exact episode, but I also found another episode this occurs on. Nichijou Episode 24...

I have another separate issue where all of season 3 of Date A Live wont download as it can't find the Japanese dub for it.
```
[INFO] Date A Live - S3E33 - Angel of the Starry Night
[INFO] Available streams (Non-Encrypted):
[#811865] English [Simulcast]
[#1062567] English [Uncut]
[ERROR] Track not selected
```

**Comment by izu-co** [comment]
Does it have a Japanese dub on Funi? Can you attach an image please?

**Comment by Jaynator495** [comment]
As far as I can tell it does, however this is odd, when I try to watch the japanese dub on funi's site it says "This is not available in your territory" - so perhaps they are having a problem? Either with showing it when it shouldn't be showing, or not playing it when it should be available. It's also only Season 3 with this problem, season 1 & 2 downloaded just fine. 
Screenshot below of it showing both english and japanese available.
![image](https://user-images.githubusercontent.com/13039635/128616330-3eae9a92-4f88-4f0c-a778-0a8ef6040281.png)

**Comment by izu-co** [comment]
Well if it doesn't work on funimation there is nothing much I can do about it. Do you have to ID of Nichijou for me?

**Comment by Jaynator495** [comment]
NIchijou's ID is #243738. Unfortunately however I just retested this and now it works fine on that episode. Strange... Intermittent issues are always the hardest to fix. If this is any indication though, seems like it's on Funimation's side. However, Episode 7 of MHA still won't download

**Comment by izu-co** [comment]
I have no clue why tho. There's no difference to other episodes within the data.

**Comment by Flippette** [comment]
Just wanted to add onto this, is it because it's selecting 2 tracks all at once?

Here's the output on Love is War S2E10
```[INFO] Kaguya-sama: Love is War - S2E10 - Kei Shirogane Can't Speak / Miyuki Shirogane Wants to Dance / Kobachi Osaragi Wants to Crack Down / Miyuki Shirogane's Dad Wants to Find Out
[INFO] Available streams (Non-Encrypted):
[#1185657] English [Simulcast]
[#1078997] Japanese [Simulcast] (selected) (using 'English' for subtitles)
[#1340881] Japanese [Simulcast] (selected)
[ERROR] HTTPError 403: FORBIDDEN```

**Comment by izu-co** [comment]
In this case it may be. Will look at it later

**Comment by izu-co** [comment]
Please reopen this issue on the main repo.
