### ISSUE TITLE
I've been working on this GUI

### ISSUE THREAD

**Issue by DragonVsKira** [izu-co/funimation-downloader-nx#25]
so i do alot off testing im not the best at it so @izu-co i will like to get your 2 cents about how i can make it any better 4 user friendly\enduser  or to make it look better lol it a WIP
<img width="1774" alt="FunDL-GUI" src="https://user-images.githubusercontent.com/35433196/126882868-f304622d-8d4f-4e0d-b22f-75d09e1aed49.png">

i may like to share it when i clean out alot of old code and stuff

did not no anywhere else to ask u this if u what u can delete this message lol
KEEP UP ALL THE HARD WORK

**Comment by izu-co** [comment]
Well, I am horrible at GUI Design. One tip I can give is to show it to a non-programmer and look if he can understand it. If so good, if not, change accordingly.

**Comment by DragonVsKira** [comment]
lol ok i have to  clean up first then fix some button name lol but thanks for the info

**Comment by izu-co** [comment]
No rush. Just out of curiosity, which language are you using?

**Comment by DragonVsKira** [comment]
vb.net i try c# but at the time it look like to much work lol with all the ) u have to add lol or something like the
y u ask?

**Comment by izu-co** [comment]
If it had been a language, I know I could've helped.

**Comment by DragonVsKira** [comment]
what language u know ?
i google Germany time it only 1:52 PM it like going on 5am lol

**Comment by izu-co** [comment]
True lol.

Well ik Java, JavaScript, Typescript as well as the basics of PHP.

**Comment by DragonVsKira** [comment]
wow that more then me i only now vb.net and a like of UE4 lol
i just make stuff for fun + i to lazy to keep typing all cmd out all the time so this GUI make a bath file for me lol

**Comment by izu-co** [comment]
Well I automated the process in Java lol
Anyway, get some sleep and have fun with the GUI.

**Comment by DragonVsKira** [comment]
i made a gui for the first funimation-downloader that Pikanet128 made longtime ago but is DL go patch / website change :(
can i see your automated process with Java?

**Comment by DragonVsKira** [comment]
can i get it 
downloads new episodes whenever they come out.
some like a call thing
i have a discord DRAGONVSKIRA#9308
if u what to keep it private

**Comment by izu-co** [comment]
There a two reason I can't do that:
The first being licenses, and the seconds the thing isn't customizable at all.
So you would need an exactly configured client to do that and oh boy I have no clue how I did it.

So sorry. I actually planned on implementing this as a feature in the downloader, but the current code is too messy for that, and I got no time for refactoring.

**Comment by DragonVsKira** [comment]
ok :( all good
can't what for that feature then

**Comment by izu-co** [comment]
Well, I don't see it coming in the new feature.
I would first need to refactor the code (possibly switching to typescript) and well that would take a lot of time.

**Comment by DragonVsKira** [comment]
No rush take your time

**Comment by izu-co** [comment]
Btw see #26  for updates on the refactoring.

**Comment by sww724** [comment]
I have been using tubedigger to get episodes from crunchy, vrv and funi, but a couple of weeks ago, the login on crunchy and funi started having issues. Crunchy warns that the browser isn't supported (embedded chromium) but I can clear the message and proceed. Funi just doesn't do anything when I click the login button. I opened an issue with the software author but no results so far. So, I have been looking for a replacement to get funi episodes and found this project. Can't say I am enthused to go to CLI after tubedigger. @DragonVsKira you might look at the user interface of tubedigger for ideas since it is very easy to get episodes. If you need a tester, I'm certainly interested.

**Comment by izu-co** [comment]
The thing is CLI is more reliable than webscraping (at least I assume that is what tubedigger is using)

**Comment by DragonVsKira** [comment]
@sww724 right now the GUI just make Batch file and run them so new people do not need to open CMD window 
"If you need a tester" it a maybe

**Comment by izu-co** [comment]
Please update me either with an issue on the main repo or with direct contact under github@izuco.dev :)
