### ISSUE TITLE
[BUG] Showing wrong quality tags (SD540) when HD is available.

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [izu-co/funimation-downloader-nx#28]
** Main info: **

Script version: 4.9.4
Show ID: 1396445
Episode ID: 0010
Command used: `funi -s 1396445 --mks -e` <-- to list them

** Additional Info: **
![Screen Shot 2021-08-10 at 12 36 02 am](https://user-images.githubusercontent.com/2242880/128724806-8ee46625-d49f-4a39-8d88-74f6aab1282f.jpg)

Notice how it shows SD540.

however when I start downloading it downloads 1080p ver
![Screen Shot 2021-08-10 at 12 37 07 am](https://user-images.githubusercontent.com/2242880/128725006-6d4ef1f9-1f1b-4ab2-b8f2-11db0be5493d.jpg)

why doesn't it just fetch the quality dimensions & use it for its tags from the available streams for each episode...

**Comment by izu-co** [comment]
Alright so I had a look into the data and Funimation actually returns `
"quality": {
        "quality": "SD",
        "height": 540
    },
`

There is other data like `mostRecentSvod` although they are the most recent and thus can be another language. Therefore, I don't see a away to implement a fix. I would wait a few days and see if Funimation is fixing this issue.
