### ISSUE TITLE
[FEATURE REQUEST] Subtitles size

### ISSUE THREAD

**Issue by Oujiii** [izu-co/funimation-downloader-nx#3]
Probably outside the scope of this project, but the subs are huge. You can change their size when watching from their website, but it downloads the default size even if you settings are from the small one (probably because the change is done to the player and not subtitles itself). If we could pick one of the available sizes, it would be great, albeit it doesn't seen possible.

Please close this if it is out of scope, like I mentioned.

Thank you.

**Comment by izu-co** [comment]
I will look into it, however I think that changing the size is due to the player.

**Comment by izu-co** [comment]
So does [this](https://github.com/izu-co/funimation-downloader-nx/commit/b2fb0e7260e19e9e32e11b67f2dc3752474fd8de) help you in any way? It lets you control the fontsize of the subtitles.

**Comment by Oujiii** [comment]
I'm gonna try and post back.

**Comment by Oujiii** [comment]
Holy shit, you are awesome! This worked, I just set `fontSize` to `35` on `cli-defaults.yml` and I'm over the moon that the subs are not covering half of my phone screen anymore!

Closing this.

**Comment by izu-co** [comment]
Glad I could help!
