### ISSUE TITLE
Support for Funimation LATAM #41

### ISSUE THREAD

**Issue by arbarbosa1979** [izu-co/funimation-downloader-nx#6]
I would like to ask you to include support for funimation LATAM - Mexico/Brazil (Spanish and Portuguese)

I tried to log in using this version and all I get is this error:

```
λ funi --auth

=== Funimation Downloader NX 4.8.1 ===

[Q] LOGIN/EMAIL: ********************************
[Q] PASSWORD   : ********************************
[ERROR] HTTPError 403: Forbidden
```

The account works normally on Funimation in the US, but if I use a latin america IP, it shows this error.

**Comment by izu-co** [comment]
Hey there.
It seems like LATAM is using a different API. I will take a look, so keep and eye on this issue for updates.

**Comment by izu-co** [comment]
Alright, I got some bad news.

For whatever reason (I think it might be CORS) the LATAM Server is not accepting my request. If I send the same request from a US IP Address, everything is fine. Therefore, I can't implement LATAM support. Please use this tool with an American IP.

**Comment by metita** [comment]
Hmmm... not sure but I think this should be implemented but only for LATAM IP Address because we cannot access US Funi without a proxy (which not everyone has access) and now Funimation expanded some more countries, if we can access through our local IP that would be great, is does not need to be an US one

**Comment by metita** [comment]
@izu-co I did a few test but wasn't able to login through the API, is needed to define a territory? (I am from Chile so I am getting CL as a territory)

**Comment by izu-co** [comment]
I already tried with setting the territory, but it didn’t work. 
I have no idea why, so I can’t add support for LATAM.

**Comment by metita** [comment]
I am trying to send the request through PostMan to get some output from the API, do you mind sending a plain-text URL like
https://prod-api-funimationnow.dadcdigital.com/api/auth/login/username&pw&whateverelse so I can test on my own?

**Comment by izu-co** [comment]
Sure, as soon as you have a working version, update me

**Comment by izu-co** [comment]
By the way @metita, if you need any help, just let me know.

**Comment by izu-co** [comment]
As a little update, it seams that the LATAM version requires strict origin, while the US version does not.

I dont know how to maipulate CORS so if anyone knows let me know to work on a fix.

**Comment by metita** [comment]
Apparently on July, Funimation will release their Apps on Mobile Devices/PS5/Switch/Smart TV so I will wait a bit to see if anything change on our end before trying to make changes as it seems nearly to impossible without doing a research (which is time consuming and my time is pretty limited x)) maybe this issue should remain open for more visibility.

**Comment by izu-co** [comment]
Sadly I also don’t have the time for research.

As it stands this issue will remain open until further notice. If anyone has a clue how to resolve this issue, please let me know.

**Comment by alfablac** [comment]
For some reason the way FormData sends this to got makes Funimation returns a unknown user error.
I had success running this for LATAM (actually Brazil) by editing the headers to the default header on the android app, on getData and the downloadPart functions
```
       headers: {
            "devicetype": "Android Phone",
            "Accept-Language": "pt-BR",
            "Accept-Encoding": "gzip",
            "User-Agent": "okhttp/3.12.1",
        }
```
While for the authorization process I used the browser user agent to generate the token, I believe the Android headers also works, due to the formData being the culprit, I believe.
```
    if(options.auth){
        gOptions.method = 'POST';
        gOptions.headers["Content-Type"] = "application/x-www-form-urlencoded; charset=UTF-8"
        gOptions.headers["Origin"] = "https://www.funimation.com"
        gOptions.headers["Content-Length"] = "49"
        gOptions.headers["Accept"] = "application/json, text/javascript, */*; q=0.01"
        gOptions.headers["Accept-Language"] = "pt-BR,en;q=0.5"
        gOptions.headers["Accept-Encoding"] = "gzip, deflate, br"
        gOptions.headers["Territory"] = "BR"
        gOptions.headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
        gOptions.body = `username=${encodeURIComponent(options.auth.user)}&password=${encodeURIComponent(options.auth.pass)}`
    }
```
As far as testing goes, the Origin attribute and the formdata POSTed as a encoded querystring makes this ok for Funi BR.

_Notice that the Accept-Language is important to get the different regions as far as I could test, as well as Territory on the authorization process_

Log is enormous, but I was able to download My Hero Academia using this command
`node funi -s 124389 -e 001 -q 7 --allSubs --allDubs`

**Comment by izu-co** [comment]
Great work.
I will test it myself and if it works you can expect an update soon.

**Comment by izu-co** [comment]
@alfablac It is still not working for me. Do you mind opening a pull request, so I can view all the changes you made and assemble a test release to publish to the LATAM Community, since I am myself are not in LATAM (btw I tried it with a VPN to Brazil)

**Comment by OryWareKyrie** [comment]
> @alfablac It is still not working for me. Do you mind opening a pull request, so I can view all the changes you made and assemble a test release to publish to the LATAM Community, since I am myself are not in LATAM (btw I tried it with a VPN to Brazil)

look at me again!!! :smile:
he gave me this file last night, if it helps [module.getdata.txt](https://github.com/izu-co/funimation-downloader-nx/files/6872823/module.getdata.txt) just replace .txt with .js and replace what is in the modules folder. but it only works with IP BR

**Comment by metita** [comment]
Well then you can change anything Brasil-related to any other LATAM country and it should work fine, ill test later today, good work tho :)

**Comment by izu-co** [comment]
Alright so I have done some testing from Germany with VPN to Brazil and I can confirm that downloading and searching works, however whenever I try to authenticate I get a 401 Unauthorized. 
Can someone actually coming from Brazil update me on whether this is related to the VPN?

**Comment by OryWareKyrie** [comment]
> Alright so I have done some testing from Germany with VPN to Brazil and I can confirm that downloading and searching works, however whenever I try to authenticate I get a 401 Unauthorized.
> Can someone actually coming from Brazil update me on whether this is related to the VPN?

sorry for the delay manin, i didn't have internet yesterday so i couldn't check the github. so I tested the authentication here and it worked for me
![image](https://user-images.githubusercontent.com/31232184/127306780-32516506-3273-4849-939f-0f02bc434930.png)

**Comment by izu-co** [comment]
So @metita did it work for you?

**Comment by metita** [comment]
@izu-co Yep, working here.

**Comment by izu-co** [comment]
Thanks for the confirmation @metita, since it doesn't seam to work with VPN I would rely on you and @OryWareKyrie (if you are both ok with that) for testing. If you are ok with it, have an eye on pull requests where I might ping you.
Can you both work with the code version from a pull request, or do you prefer a release zip?

**Comment by alfablac** [comment]
> Thanks for the confirmation @metita, since it doesn't seam to work with VPN I would rely on you and @OryWareKyrie (if you are both ok with that) for testing. If you are ok with it, have an eye on pull requests where I might ping you.
> Can you both work with the code version from a pull request, or do you prefer a release zip?

@izu-co You can also ping me on the PR and I will be able to check.

**Comment by OryWareKyrie** [comment]
> Thanks for the confirmation @metita, since it doesn't seam to work with VPN I would rely on you and @OryWareKyrie (if you are both ok with that) for testing. If you are ok with it, have an eye on pull requests where I might ping you.
> Can you both work with the code version from a pull request, or do you prefer a release zip?

I am available too. but I notice that, I don't know anything about programming. the grandma master of programming is the @alfablac 😸

**Comment by izu-co** [comment]
Should be added into the main repo
