### ISSUE TITLE
Add support for multi audio/ multi dub and subtitels

### ISSUE THREAD

**Issue by DAREK0N** [izu-co/funimation-downloader-nx#8]
Add support for downloading multiple audio files. Since the audio from newer shows are now separated from the main video file, it should be possible to download multiple dub languishes (e.g. English and Japanese).
It would also be nice if it were possible to download subtitles for the other dub languishes other than Japanese.

**Comment by izu-co** [comment]
Please see #10 for progress

**Comment by izu-co** [comment]
Please download the new [release](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.9.0) and test it. 

If you find any errors, open a new issue, please.
